name: test


on: [push, pull_request, workflow_dispatch]

jobs:  
  indent:
    name: indent
    runs-on: [ubuntu-24.04]

    strategy:
      matrix:
        python-versions: ['3.12']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}
    - name: make indent
      run: |
        python -m pip install black
        ./contrib/utilities/indent
        git diff > changes-astyle.diff
    - name: archive indent results
      uses: actions/upload-artifact@v4
      with:
        name: changes-astyle.diff
        path: changes-astyle.diff
    - name: check indentation
      run: |
        git diff --exit-code

  linux:
    name: test
    runs-on: [ubuntu-24.04]

    strategy:
      matrix:
        python-versions: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}
    - name: setup
      run: |
        sudo apt update && sudo apt install --yes \
         numdiff \
         texlive \
         texlive-latex-extra
        python -m pip install --upgrade pip
        pip install autograd # this is optional
        python --version
    - name: test
      run: |
        PYTHON=python ./test.sh

  linux_full_pycddlib:
    name: test with full pycddlib
    runs-on: [ubuntu-24.04]

    strategy:
      matrix:
        python-versions: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-versions }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-versions }}
    - name: setup
      run: |
        sudo apt update && sudo apt install --yes \
         libcdd-dev \
         libgmp-dev \
         numdiff \
         texlive \
         texlive-latex-extra
        python -m pip install --upgrade pip
        pip install pycddlib autograd # this is optional
        python --version
    - name: test with full pycddlib
      run: |
        PYTHON=python ./test.sh
